### ISSUE TITLE
Need to get total pages

### ISSUE THREAD

**Issue by pandora-house** [fayis672/epub_viewer#11]
Nice job man!  look's like here exist some problem, probably you can start from this https://github.com/futurepress/epub.js/issues/744#issuecomment-492300092

**Comment by fayis672** [comment]
Page number depends on many things like, screen size, font size spread etc. So it's hard to get accurate page numbers, instead, it will be possible to get progress in percentage, I will be adding that soon.

**Comment by Essenbay** [comment]
Any progress? Is there any other way to get progress?

**Comment by fayis672** [comment]
Added `progress` in `EpubLocation`, which will be available in  `onRelocated` callback and via `getCurrentLocation` function. Also added a method `toProgressPercentage` to move to the given progress. Available in version `1.1.3`
