### ISSUE TITLE
load from local file

### ISSUE THREAD

**Issue by pandora-house** [fayis672/epub_viewer#12]
As I understand, epubjs allow to get book from bytesArray

**Comment by rodrigocanepa** [comment]
There is a fork here with an interesting option to load local files:

https://github.com/polymorph001/epub_viewer

but is not completed yet because I can't read the chapters from that fork and the callbacks are no working well

**Comment by fayis672** [comment]
> There is a fork here with an interesting option to load local files:
> 
> https://github.com/polymorph001/epub_viewer
> 
> but is not completed yet because I can't read the chapters from that fork and the callbacks are no working well

This seems to be a good approch
