### ISSUE TITLE
The shared flag to bind() needs to be true if binding multiple times on the same (address, port) combination.

### ISSUE THREAD

**Issue by Esdeath** [fayis672/epub_viewer#18]
flutter: Error: SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be true if binding multiple times on the same (address, port) combination.), address = 127.0.0.1, port = 8080 #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)

I use navigate to the epub  page ,its ok,then i  back to the prev page, then navigate to the epub page, its error

**Comment by fayis672** [comment]
Please provide a minimal reproduce code and `flutter doctor -v`  outputs
