### ISSUE TITLE
chapters on controller was empty

### ISSUE THREAD

**Issue by mhnadimy** [fayis672/epub_viewer#31]
`epubController.chapters` returning empty value 

my Code : 
```
onEpubLoaded: () async {
 print('loaded');
 print(epubController.chapters.length);
 setState(() {
  isLoading = false;
 });
}
```

OUT PUT : 

```
flutter: loaded
flutter: 0
```

**Comment by mhnadimy** [comment]
i think problem on `parseChapters` function :D

**Comment by fayis672** [comment]
Please use `onChaptersLoaded` callback to get chapters

**Comment by mhnadimy** [comment]
thanks for your help 
but it doesn't work 

check your example file i clone and edit your file :)

**Comment by fayis672** [comment]
The existing example is working correctly for me, you can use either `onChaptersLoaded` or `getChapters()` method from epubController to get chapters, if still don't work please share tthe code snippet
